Swap the command names of pkg build and pkg make

diff --git a/base/pkg/actions/build b/base/pkg/actions/build
--- a/base/pkg/actions/build
+++ b/base/pkg/actions/build
@@ -1,52 +1,69 @@
-unset SRC
-while getopts :ds: OPTION; do
+while getopts :d OPTION; do
   case $OPTION in
     d)
       DEBUG=1
-      ;;
-    s)
-      if [[ -d $OPTARG ]]; then
-        SRC=$(cd -- "$OPTARG" && echo $PWD)
-      else
-        die "Prepared build tree $OPTARG not found"
-      fi
       ;;
   esac
 done
 shift $(($OPTIND - 1))
 
-if [[ $# -lt 2 ]]; then
+if [[ $# -lt 1 ]]; then
   die "$(< $LIBRARY/help)"
 fi
 
-setup "$1" "${@:3}"
+setup "$@"
 
-if mkdir -p -- "$2" 2>/dev/null; then
-  DST=$(cd -- "$2" && echo $PWD)
+mkdir -p "$CACHEDIR" "$IMGDIR"
+ROOT=$(mktemp -d "$IMGDIR/${1##*/}.XXXXXX")
+if [[ -n $DEBUG ]]; then
+  trap 'echo "Build root left in $ROOT" >&2' EXIT
 else
-  die "Failed to create directory $2"
+  trap 'rm -f -r --one-file-system "$ROOT"' EXIT
 fi
 
-if ( cd "$DST" && set -- * && [[ $# -gt 0 ]] ); then
-  die "Cannot build image in $DST: directory is not empty"
-elif [[ -n $DEBUG ]]; then
-  trap 'echo "Incomplete image left in $DST" >&2' ERR
-else
-  trap '[[ -n $DST ]] && find "$DST" -depth -mindepth 1 -delete' ERR
-fi
+mkdir -m 0755 -p "$ROOT"/{bin,cache,dst,dev,etc,lib,pkg,proc,src,sys}
+mkdir -m 1777 -p "$ROOT"/{run/shm,var/tmp}
+cp -L -R /etc/{protocols,resolv.conf,services,ssl} "$ROOT/etc/"
+cp $LIBRARY/skel/{passwd,group} "$ROOT/etc/"
+ln -s var/tmp "$ROOT/tmp"
 
-if [[ -z $SRC ]]; then
-  SRC=$(mktemp -d --tmpdir src-XXXXXX)
-  if [[ -n $DEBUG ]]; then
-    trap 'echo "Failed build tree left in $SRC" >&2' EXIT
+for REQUIRED in "$PKGDIR"/base/* \
+    $(require() { echo "$1"; } && source "$PKG/build"); do
+  if [[ -d "$IMGDIR/${REQUIRED##*/}" ]]; then
+    cp -a -l -T "$IMGDIR/${REQUIRED##*/}" "$ROOT"
   else
-    trap '[[ -n $SRC ]] && find "$SRC" -depth -delete' EXIT
+    die "Build requirement ${REQUIRED##*/} not found in $IMGDIR"
   fi
-fi
+done
 
-if ( cd "$SRC" && set -- * && [[ $# -eq 0 ]] ); then
-  ( source "$PKG/build" && cd "$SRC" && prepare )
-fi
+( trap 'umount -l "$ROOT"' EXIT
 
-( source "$PKG/build" && cd "$SRC" && build 2>&1 )
-( source "$PKG/build" && cd "$DST" && tidy )
+  mount -B --make-slave "$ROOT" "$ROOT"
+  mount -B --make-slave "$ROOT/dst" "$ROOT/dst"
+  mount -B --make-slave "$ROOT/run" "$ROOT/run"
+  mount -B --make-slave "$ROOT/src" "$ROOT/src"
+  mount -B --make-slave "$ROOT/var/tmp" "$ROOT/var/tmp"
+
+  mount -R --make-rslave /dev "$ROOT/dev"
+  mount -R --make-rslave /proc "$ROOT/proc"
+  mount -R --make-rslave /sys "$ROOT/sys"
+  mount -R --make-rslave "$CACHEDIR" "$ROOT/cache"
+  mount -R --make-rslave "$PKGDIR" "$ROOT/pkg"
+
+  mount -B -o remount,ro "$ROOT"
+  mount -B -o remount,ro "$ROOT/pkg"
+
+  chroot $ROOT env -i CACHEDIR=/cache HOME=/ PATH=/bin PKGDIR=/pkg \
+    TERM="$TERM" pkg make ${DEBUG:+-d} -s /src "$1" /dst "${@:2}"
+)
+
+if [[ -n $DEBUG ]]; then
+  echo "Debug mode: not replacing existing image"
+elif [[ -e "$IMGDIR/${1##*/}" ]]; then
+  echo "Replacing existing image in $IMGDIR/${1##*/}"
+  rm -f -r "$IMGDIR/${1##*/}"
+  mv -- "$ROOT/dst" "$IMGDIR/${1##*/}"
+else
+  echo "Installing new image in $IMGDIR/${1##*/}"
+  mv -- "$ROOT/dst" "$IMGDIR/${1##*/}"
+fi
