Always build packages in fixed encapsulated trees
Build scripts should really quote $DST, $PKG and $SRC in case they
contain whitespace or other special characters, making them much
noisier. In practice, however, builds are almost always encapsulated
with $DST set to /dst, $PKG set to /pkg and $SRC set to /src.

Define that packages are always built in these fixed encapsulated trees,
adjusting the pkg tool and package tree to reflect this simplification.

diff --git a/base/pkg/actions/prepare b/base/pkg/actions/prepare
--- a/base/pkg/actions/prepare
+++ b/base/pkg/actions/prepare
@@ -1,29 +1,43 @@
-while getopts :d OPTION; do
-  case $OPTION in
-    d)
-      DEBUG=1
-      ;;
-  esac
-done
-shift $(($OPTIND - 1))
-
 if [[ $# -lt 1 ]]; then
   die "$(< $LIBRARY/help)"
+elif [[ $2 != ?(-) ]] && [[ -e "$2" ]]; then
+  die "Cannot unpack sources: $2 already exists"
 fi
 
-setup "$1" "${@:3}"
+PKG=$(locate "$PKGDIR" "$1")
+mkdir -p "$CACHEDIR" "$IMGDIR"
 
-if [[ $2 == ?(-) ]]; then
-  SRC=$(mktemp -d)
-  trap 'rm -f -r --one-file-system "$SRC"' EXIT
-elif mkdir -p -- "$2" 2>/dev/null; then
-  SRC=$(cd -- "$2" && echo $PWD)
-else
-  die "Failed to create directory $2"
+ROOT=$(mktemp -d "$IMGDIR/${1##*/}.XXXXXX")
+trap 'rm -f -r --one-file-system "$ROOT"' EXIT
+
+mkdir -m 0755 -p "$ROOT"/{bin,dev,etc,lib,proc,run,sys,var}
+mkdir -m 0755 -p "$ROOT"/{pkg,src,var/cache}
+mkdir -m 1777 -p "$ROOT"/{run/shm,var/tmp}
+ln -s var/tmp "$ROOT/tmp"
+
+cp -L -R /etc/{protocols,resolv.conf,services,ssl} "$ROOT/etc/"
+cp "$LIBRARY/skel/passwd" "$LIBRARY/skel/group" "$ROOT/etc/"
+
+for IMG in "$PKGDIR"/base/*; do
+  if [[ -d "$IMGDIR/${IMG##*/}" ]]; then
+    cp -a -l -T "$IMGDIR/${IMG##*/}" "$ROOT"
+  else
+    die "Base image ${IMG##*/} not found in $IMGDIR"
+  fi
+done
+
+mapfile -t REQUIRED \
+  < <(encapsulate "$ROOT" pkg helper requirements "${@:3}")
+for IMG in "${REQUIRED[@]}"; do
+  if [[ -n ${IMG%%+(/)} ]] && [[ -d "$IMGDIR/$IMG" ]]; then
+    cp -a -l -T "$IMGDIR/$IMG" "$ROOT"
+  else
+    die "Required image $IMG not found in $IMGDIR"
+  fi
+done
+
+encapsulate "$ROOT" pkg helper prepare "${@:3}"
+
+if [[ $2 != ?(-) ]]; then
+  mv "$ROOT/src" "$2"
 fi
-
-if ( cd "$SRC" && set -- * && [[ $# -gt 0 ]] ); then
-  die "Cannot unpack sources in $SRC: directory is not empty"
-fi
-
-( source "$PKG/build" && cd "$SRC" && prepare )
diff --git a/base/pkg/lib/shared b/base/pkg/lib/shared
--- a/base/pkg/lib/shared
+++ b/base/pkg/lib/shared
@@ -1,4 +1,5 @@
 declare -A FEATURES=()
+declare -A REQUIREMENTS=()
 
 apply() {
   local DIR OPTARG OPTIND OPTION STRIP=1
@@ -74,6 +75,36 @@ enabled() {
   done
 }
 
+encapsulate() (
+  mount -B --make-slave "$1" "$1"
+  trap 'umount -l "$1"' EXIT
+
+  mount -B --make-slave "$1/run" "$1/run"
+  mount -B --make-slave "$1/var/tmp" "$1/var/tmp"
+  mount -R --make-rslave /dev "$1/dev"
+  mount -R --make-rslave /proc "$1/proc"
+  mount -R --make-rslave /sys "$1/sys"
+
+  if [[ -d $1/dst ]]; then
+    mount -B --make-slave "$1/dst" "$1/dst"
+  fi
+
+  if [[ -d $1/pkg ]] && [[ -n $PKG ]]; then
+    mount -R --make-rslave "$PKG" "$1/pkg"
+  fi
+
+  if [[ -d $1/src ]]; then
+    mount -R --make-rslave "${SRC:-$1/src}" "$1/src"
+  fi
+
+  if [[ -d $1/var/cache ]]; then
+    mount -R --make-rslave "${CACHEDIR:-$1/var/cache}" "$1/var/cache"
+  fi
+
+  mount -B -o remount,ro "$1"
+  chroot "$1" env -i HOME=/ PATH=/bin TERM="$TERM" "${@:2}"
+)
+
 feature() {
   if [[ -z ${FEATURES[$1]+defined} ]]; then
     return 1
@@ -132,6 +163,23 @@ hashtree() {
   } | b2sum -l 256 | cut -b 1-64
 }
 
+locate() {
+  if [[ $2 == ?(.|..)/* ]]; then
+    if [[ ! -f $2/build ]]; then
+      die "Package $2 not found"
+    fi
+    echo "$2"
+  else
+    declare -a PKG=("$1"/**/"$2/build")
+    if [[ ${#PKG[@]} -lt 1 ]]; then
+      die "Package $2 not found"
+    elif [[ ${#PKG[@]} -gt 1 ]]; then
+      die "Ambiguous package $2: ${PKG[*]}"
+    fi
+    echo "${PKG%/build}"
+  fi
+}
+
 maybe() {
   [[ ${@:$#} == "--" ]] || "$@"
 }
@@ -148,43 +196,27 @@ prepare() {
   die "Package does not define prepare()"
 }
 
-require() { :; }
+require() {
+  while [[ $# -gt 0 ]]; do
+    REQUIREMENTS[$1]=1
+    shift
+  done
+}
 
 setup() {
   set -o allexport
   unset CFLAGS LDFLAGS
   CHOST=$(cc -dumpmachine)
   MAKEFLAGS=-j$((1 + $(nproc)))
-  CACHEDIR=${CACHEDIR:-$HOME/cache}
-  IMGDIR=${IMGDIR:-$HOME/img}
-  PKGDIR=${PKGDIR:-$HOME/pkg}
   set +o allexport
 
-  if [[ $1 == ?(.|..)/* ]]; then
-    if [[ -f $1/build ]]; then
-      PKG=$1
-    else
-      die "Package $1 not found"
-    fi
-  elif [[ $1 == ?(-) ]]; then
-    PKG=-
-  else
-    PKG=("$PKGDIR"/**/"$1/build")
-    if [[ ${#PKG[@]} -lt 1 ]]; then
-      die "Package $1 not found"
-    elif [[ ${#PKG[@]} -gt 1 ]]; then
-      die "Ambiguous package $1 found in ${PKG[*]}"
-    else
-      PKG=${PKG%/build}
-    fi
-  fi
-
-  while shift && [[ $# -gt 0 ]]; do
+  while [[ $# -gt 0 ]]; do
     if [[ $1 == no-* ]]; then
       disable "${1#no-}"
     else
       enable "$1"
     fi
+    shift
   done
 }
 
