Tag the pkg build debug shell prompt
When a forced build fails and drops into a debug shell, tag the prompt
with [build] so it is more obvious that we haven't dropped straight back
to the root shell on the build host.

diff --git a/pkg/actions/build b/pkg/actions/build
--- a/pkg/actions/build
+++ b/pkg/actions/build
@@ -67,7 +67,7 @@ helper() {
   setup /pkg "${@:2}"
 
   if enabled force; then
-    trap '(( $? )) && echo "Build failed: starting debug shell" && bash' EXIT
+    trap '(( $? )) && echo "Build failed" && PS1="[build] \\$ " bash' EXIT
   else
     trap '(( $? )) && echo "Build failed"' EXIT
   fi
