Move pkg helpers into their respective actions

diff --git a/pkg/actions/build b/pkg/actions/build
--- a/pkg/actions/build
+++ b/pkg/actions/build
@@ -1,58 +1,111 @@
-unset DEBUG SRC
-while getopts :ds: OPTION; do
-  case $OPTION in
-    d)
-      DEBUG=1
-      ;;
-    s)
-      if [[ -d $OPTARG ]]; then
-        SRC=$OPTARG
+action() {
+  unset DEBUG SRC
+  while getopts :ds: OPTION; do
+    case $OPTION in
+      d)
+        DEBUG=1
+        ;;
+      s)
+        if [[ -d $OPTARG ]]; then
+          SRC=$OPTARG
+        else
+          die "Prepared source tree $OPTARG not found"
+        fi
+        ;;
+    esac
+  done
+  shift $(($OPTIND - 1))
+
+  if [[ $# -lt 1 ]]; then
+    die "$(< $LIBRARY/help)"
+  fi
+
+  PKG=$(locate "$PKGDIR" "$1")
+  mkdir -p "$CACHEDIR" "$IMGDIR"
+
+  ROOT=$(mktemp -d "$IMGDIR/${PKG##*/}.XXXXXX")
+  chmod 0755 "$ROOT"
+
+  if [[ -n $DEBUG ]]; then
+    trap 'echo "Build root left in $ROOT" >&2' EXIT
+  else
+    trap 'rm -f -r --one-file-system "$ROOT"' EXIT
+  fi
+
+  helper() {
+    PKG=$PKG SRC=$SRC pkg sandbox "$ROOT" pkg "$@"
+  }
+
+  populate "$ROOT" build
+  mkdir -p "$ROOT/img/${PKG##*/}" "$ROOT/pkg" "$ROOT/src"
+  ln -s "img/${PKG##*/}" "$ROOT/dst"
+  mapfile -t REQUIRED < <(helper requirements "${PKG##*/}" "${@:2}")
+  populate "$ROOT" "${REQUIRED[@]}"
+  helper build "${PKG##*/}" "${@:2}"
+
+  if [[ -n $DEBUG ]]; then
+    echo "Debug mode: not installing or replacing images"
+  else
+    for IMG in "$ROOT"/img/*; do
+      if [[ -e "$IMGDIR/${IMG##*/}" ]]; then
+        echo "Replacing existing image in $IMGDIR/${IMG##*/}"
+        rm -f -r "$IMGDIR/${IMG##*/}"
+        mv "$IMG" "$IMGDIR/${IMG##*/}"
       else
-        die "Prepared source tree $OPTARG not found"
+        echo "Installing new image in $IMGDIR/${IMG##*/}"
+        mv "$IMG" "$IMGDIR/${IMG##*/}"
       fi
-      ;;
-  esac
-done
-shift $(($OPTIND - 1))
-
-if [[ $# -lt 1 ]]; then
-  die "$(< $LIBRARY/help)"
-fi
-
-PKG=$(locate "$PKGDIR" "$1")
-mkdir -p "$CACHEDIR" "$IMGDIR"
-
-ROOT=$(mktemp -d "$IMGDIR/${PKG##*/}.XXXXXX")
-chmod 0755 "$ROOT"
-
-if [[ -n $DEBUG ]]; then
-  trap 'echo "Build root left in $ROOT" >&2' EXIT
-else
-  trap 'rm -f -r --one-file-system "$ROOT"' EXIT
-fi
-
-helper() {
-  PKG=$PKG SRC=$SRC pkg sandbox "$ROOT" pkg helper "$@"
+    done
+  fi
 }
 
-populate "$ROOT" build
-mkdir -p "$ROOT/img/${PKG##*/}" "$ROOT/pkg" "$ROOT/src"
-ln -s "img/${PKG##*/}" "$ROOT/dst"
-mapfile -t REQUIRED < <(helper requirements "${PKG##*/}" "${@:2}")
-populate "$ROOT" "${REQUIRED[@]}"
-helper build "${PKG##*/}" "${@:2}"
-
-if [[ -n $DEBUG ]]; then
-  echo "Debug mode: not installing or replacing images"
-else
-  for IMG in "$ROOT"/img/*; do
-    if [[ -e "$IMGDIR/${IMG##*/}" ]]; then
-      echo "Replacing existing image in $IMGDIR/${IMG##*/}"
-      rm -f -r "$IMGDIR/${IMG##*/}"
-      mv "$IMG" "$IMGDIR/${IMG##*/}"
+helper() {
+  image() (
+    if [[ $2 == contains ]] && [[ $1 != ?(-) ]]; then
+      cd /dst && mkdir -p "/img/$1"
+      while [[ $# -gt 2 ]]; do
+        cp -a -l -t "/img/$1" --parents -- "${3#/dst/}"
+        rm -f -r -- "${3#/dst/}"
+        set -- "$1" "$2" "${@:4}"
+      done
+    elif [[ $2 == requires ]] && [[ $# -gt 2 ]]; then
+      if [[ $1 == ?(-) ]]; then
+        mkdir -p /dst/info
+        printf '%s\n' "${@:3}" >>/dst/info/requirements
+      else
+        mkdir -p "/img/$1/info"
+        printf '%s\n' "${@:3}" >>/img/$1/info/requirements
+      fi
     else
-      echo "Installing new image in $IMGDIR/${IMG##*/}"
-      mv "$IMG" "$IMGDIR/${IMG##*/}"
+      die "Invalid command: image $*"
+    fi
+  )
+
+  PKG=/pkg
+  setup "${@:2}"
+  source /pkg/build
+
+  if ( set -- /src/* && [[ $# -eq 0 ]] ); then
+    cd /src && prepare "${@:2}"
+    find /src -depth -exec touch -r /src {} +
+  fi
+  cd /src && build "${@:2}" 2>&1
+
+  tidy /img/*
+  for IMG in /img/*; do
+    if [[ -d "$IMG" ]]; then
+      mkdir -p "$IMG/info"
+      printf '%s\n' "$2" >"$IMG/info/source"
+    fi
+    if [[ -f "$IMG/info/requirements" ]]; then
+      sort -o "$IMG/info/requirements" -u "$IMG/info/requirements"
     fi
   done
+  find /img -depth -exec touch -d $(date +@%s) {} +
+}
+
+if [[ $$ -eq 1 ]]; then
+  helper "$@"
+else
+  action "$@"
 fi
diff --git a/pkg/actions/check b/pkg/actions/check
--- a/pkg/actions/check
+++ b/pkg/actions/check
@@ -1,41 +1,76 @@
-unset JOBS
-while getopts :p: OPTION; do
-  case $OPTION in
-    p)
-      if [[ $OPTARG == [1-9]*([0-9]) ]]; then
-        JOBS=$OPTARG
-      else
-        die "Invalid parallel job limit: $OPTARG"
-      fi
-      ;;
-  esac
-done
-shift $(($OPTIND - 1))
-
-mkdir -p "$CACHEDIR" "$IMGDIR"
-ROOT=$(mktemp -d "$IMGDIR/root.XXXXXX")
-trap 'rm -f -r --one-file-system "$ROOT"' EXIT
-chmod 0755 "$ROOT"
-
-populate "$ROOT" build
-mkdir -p "$ROOT/pkg"
-
-check() {
-  while set -- "$1" $(jobs -p) && [[ $# -gt ${JOBS:-16} ]]; do
-    wait -n
+action() {
+  unset JOBS
+  while getopts :p: OPTION; do
+    case $OPTION in
+      p)
+        if [[ $OPTARG == [1-9]*([0-9]) ]]; then
+          JOBS=$OPTARG
+        else
+          die "Invalid parallel job limit: $OPTARG"
+        fi
+        ;;
+    esac
   done
-  PKG=$1 pkg sandbox "$ROOT" pkg helper check "${1##*/}" &
+  shift $(($OPTIND - 1))
+
+  mkdir -p "$CACHEDIR" "$IMGDIR"
+  ROOT=$(mktemp -d "$IMGDIR/root.XXXXXX")
+  trap 'rm -f -r --one-file-system "$ROOT"' EXIT
+  chmod 0755 "$ROOT"
+
+  populate "$ROOT" build
+  mkdir -p "$ROOT/pkg"
+
+  check() {
+    while set -- "$1" $(jobs -p) && [[ $# -gt ${JOBS:-16} ]]; do
+      wait -n
+    done
+    PKG=$1 pkg sandbox "$ROOT" pkg check "${1##*/}" &
+  }
+
+  if [[ $# -eq 0 ]]; then
+    trap wait EXIT
+    for PKGBUILD in "$PKGDIR"/*/build; do
+      check "${PKGBUILD%/build}"
+    done
+  else
+    trap wait EXIT
+    for PKG in "$@"; do
+      PKG=$(locate "$PKGDIR" "$PKG")
+      check "$PKG"
+    done
+  fi | sort -k 1 -t :
 }
 
-if [[ $# -eq 0 ]]; then
-  trap wait EXIT
-  for PKGBUILD in "$PKGDIR"/*/build; do
-    check "${PKGBUILD%/build}"
-  done
+helper() {
+  match() {
+    PATTERN=$3 REPLACE=${4:-\\1} gawk -e '{
+      while (ENVIRON["PATTERN"] && match($0, ENVIRON["PATTERN"])) {
+        print gensub(ENVIRON["PATTERN"], ENVIRON["REPLACE"], 1,
+          substr($0, RSTART, RLENGTH));
+        $0 = substr($0, RSTART + RLENGTH);
+      }
+    }' | sort -V | tail -n 1 | if ! read VERSION; then
+      warn "$PKGNAME: $1 not found"
+    elif [[ $2 != $VERSION ]]; then
+      echo "$PKGNAME: $1 $VERSION available"
+    fi
+  }
+
+  url() {
+    exec < <(curl -f -m 30 -s -L -- "$1" || die "$PKGNAME: failed to get $1")
+  }
+
+  PKG=/pkg
+  PKGNAME=$1
+  setup "${@:2}"
+  source /pkg/build
+
+  cd /pkg && check "${@:2}" </dev/null
+}
+
+if [[ $$ -eq 1 ]]; then
+  helper "$@"
 else
-  trap wait EXIT
-  for PKG in "$@"; do
-    PKG=$(locate "$PKGDIR" "$PKG")
-    check "$PKG"
-  done
-fi | sort -k 1 -t :
+  action "$@"
+fi
diff --git a/pkg/actions/prepare b/pkg/actions/prepare
--- a/pkg/actions/prepare
+++ b/pkg/actions/prepare
@@ -1,26 +1,46 @@
-if [[ $# -lt 1 ]]; then
-  die "$(< $LIBRARY/help)"
-elif [[ $2 != ?(-) ]] && [[ -e "$2" ]]; then
-  die "Cannot unpack sources: $2 already exists"
-fi
+action() {
+  if [[ $# -lt 1 ]]; then
+    die "$(< $LIBRARY/help)"
+  elif [[ $2 != ?(-) ]] && [[ -e "$2" ]]; then
+    die "Cannot unpack sources: $2 already exists"
+  fi
 
-PKG=$(locate "$PKGDIR" "$1")
-mkdir -p "$CACHEDIR" "$IMGDIR"
+  PKG=$(locate "$PKGDIR" "$1")
+  mkdir -p "$CACHEDIR" "$IMGDIR"
 
-ROOT=$(mktemp -d "$IMGDIR/${1##*/}.XXXXXX")
-trap 'rm -f -r --one-file-system "$ROOT"' EXIT
-chmod 0755 "$ROOT"
+  ROOT=$(mktemp -d "$IMGDIR/${1##*/}.XXXXXX")
+  trap 'rm -f -r --one-file-system "$ROOT"' EXIT
+  chmod 0755 "$ROOT"
 
-helper() {
-  PKG=$PKG SRC= pkg sandbox "$ROOT" pkg helper "$@"
+  helper() {
+    PKG=$PKG SRC= pkg sandbox "$ROOT" pkg "$@"
+  }
+
+  populate "$ROOT" build
+  mkdir -p "$ROOT"/{pkg,src}
+  mapfile -t REQUIRED < <(helper requirements "${PKG##*/}" "${@:3}")
+  populate "$ROOT" "${REQUIRED[@]}"
+  helper prepare "${PKG##*/}" "${@:3}"
+
+  if [[ $2 != ?(-) ]]; then
+    mv "$ROOT/src" "$2"
+  fi
 }
 
-populate "$ROOT" build
-mkdir -p "$ROOT"/{pkg,src}
-mapfile -t REQUIRED < <(helper requirements "${PKG##*/}" "${@:3}")
-populate "$ROOT" "${REQUIRED[@]}"
-helper prepare "${PKG##*/}" "${@:3}"
+helper() {
+  PKG=/pkg
+  setup "${@:2}"
+  source /pkg/build
 
-if [[ $2 != ?(-) ]]; then
-  mv "$ROOT/src" "$2"
+  if ( set -- /src/* && [[ $# -ne 0 ]] ); then
+    die "Cannot unpack sources: directory is not empty"
+  fi
+  cd /src && prepare "${@:2}"
+  find /src -depth -exec touch -r /src {} +
+}
+
+if [[ $$ -eq 1 ]]; then
+  helper "$@"
+else
+  action "$@"
 fi
