Obey our own style rules in pkg check

diff --git a/pkg/actions/check b/pkg/actions/check
--- a/pkg/actions/check
+++ b/pkg/actions/check
@@ -63,7 +63,11 @@ helper() {
   }
 
   url() {
-    exec < <(curl -f -m 30 -s -L -- "$1" || die "$PKGNAME: failed to get $1")
+    exec < <(
+      if ! curl -f -m 30 -s -L -- "$1"; then
+        die "$PKGNAME: failed to get $1"
+      fi
+    )
   }
 
   cd /pkg
