Teach update-etc how to populate passwd and group

diff --git a/base/pkg/bin/update-etc b/base/pkg/bin/update-etc
--- a/base/pkg/bin/update-etc
+++ b/base/pkg/bin/update-etc
@@ -1,4 +1,15 @@
-#!/bin/bash -e
+#!/bin/bash
+
+set -e -o pipefail
+shopt -s dotglob extglob globstar nullglob
+unset LANG LC_{ALL,COLLATE,CTYPE,MESSAGES,MONETARY,NUMERIC,TIME}
+
+if [[ ! -d ${0%/*}/../lib/pkg ]]; then
+  echo "Failed to identify library path" >&2
+  exit 1
+fi
+
+LIBRARY=$(cd -- "${0%/*}/../lib/pkg" && echo $PWD)
 
 echo "Updating /etc/protocols" 
 curl -s -L https://salsa.debian.org/md/netbase/-/raw/master/etc/protocols \
@@ -11,7 +22,6 @@ else
   rm /etc/protocols.tmp
   exit 1
 fi
-
 
 echo "Updating /etc/services"
 curl -s -L https://salsa.debian.org/md/netbase/-/raw/master/etc/services \
@@ -34,4 +44,20 @@ else
   echo "Updated /etc/ssl/cert.pem failed sanity check" >&2
   rm /etc/ssl/cert.tmp
   exit 1
+fi
+
+echo "Updating /etc/group"
+if [[ -f /etc/group ]]; then
+  awk -F : '!uniq[$1]++' {/etc,$LIBRARY/skel}/group >/etc/group.tmp
+  mv /etc/group.tmp /etc/group
+else
+  cp $LIBRARY/skel/group /etc/group
+fi
+
+echo "Updating /etc/passwd"
+if [[ -f /etc/passwd ]]; then
+  awk -F : '!uniq[$1]++' {/etc,$LIBRARY/skel}/passwd >/etc/passwd.tmp
+  mv /etc/passwd.tmp /etc/passwd
+else
+  cp $LIBRARY/skel/passwd /etc/passwd
 fi
